#### 1. The hash() function in Python is used to generate a unique integer value (called a hash value) for an object. This function is important in many areas, particularly in data structures like dictionaries and sets, where it helps in quick data retrieval.

##### 1: input(): Reads a line of input from the user.
##### 2: .strip(): Removes any leading or trailing whitespace from the input.
##### 3: .split(): Splits the input string into a list of substrings based on whitespace.
##### 4: map(int, ...): Applies the int function to each substring, converting them to integers.
##### 5: list(...): Converts the map object into a list.

In [14]:
#This ensures that the code block runs only when the script is executed directly, not when imported as a module.
if __name__ == '__main__':
    #Reads the number of integers that will be input.
    n = int(input())  # Read the number of elements
    #Reads the space-separated integers, converts them to integers, and returns an iterator.
    integer_list = map(int, input().split())  # Read space-separated integers and convert them to integers
    
    # Create a tuple from the list of integers .. Converts the iterator into a tuple.
    t = tuple(integer_list)
    
    # Compute the hash of the tuple
    result = hash(t)
    
    # Print the hash result
    print(result) #Outputs the hash result.

 2
 1 2


-3550055125485641917


##### 2. NUMPY Function

##### You can compute the matrix product of two arrays 𝐴 and 𝐵 using NumPy's dot() function. This function computes the matrix multiplication between two arrays.
1.Read the size N of the matrices.

2.Input the elements of matrix A and matrix B.

3.Use numpy.dot() to compute the matrix product of A and B.

4.Print the result

In [20]:
import numpy

A = numpy.array([1, 2])
B = numpy.array([3, 4])

print(numpy.dot(A, B))

11


In [17]:
import numpy

A = numpy.array([ 1, 2 ])
B = numpy.array([ 3, 4 ])

print (numpy.cross(A, B))

-2


In [19]:
import numpy as np

# Input the size of the matrices
N = int(input())

#We first read the integer N, which defines the size of the square matrices.
# Input matrix A
A = []
for _ in range(N):
    A.append(list(map(int, input().split())))

#We read the next N lines to populate matrix A and the next N lines to populate matrix B.
# Input matrix B
B = []
for _ in range(N):
    B.append(list(map(int, input().split())))

#We then convert the input lists into NumPy arrays.
# Convert lists to numpy arrays
A = np.array(A)
B = np.array(B)

#Using numpy.dot(A, B), we compute the matrix product of A and B.
# Compute matrix multiplication
result = np.dot(A, B)

#we print the result
# Output the result
print(result)

 2
 1 2
 3 4
 1 2
 3 4


[[ 7 10]
 [15 22]]


In [22]:
import numpy

A = numpy.array([0, 1])
B = numpy.array([3, 4])

print (numpy.inner(A, B))     #Output : 4

4


In [23]:
import numpy

A = numpy.array([0, 1])
B = numpy.array([3, 4])

print (numpy.outer(A, B))

[[0 0]
 [3 4]]


#### inner product=A[0]×B[0]+A[1]×B[1]

#### Substituting the values from A and B:

#### inner() = a1 x b1 +a2 X b2 +...+an x bn

#### 0×2+1×3=0+3=3

In [24]:
import numpy as np
A=np.array([0,1])
B=np.array([2,3])

print(np.inner(A,B))
print(np.outer(A,B))

3
[[0 0]
 [2 3]]


#### 0x2   0x3       0  0
#### 1x2   1x3  =    2  3

In [31]:
## Another Solution:

import numpy as np
A=np.array(input().split(), dtype=int)
B=np.array(input().split(), dtype=int)

print(np.inner(A,B))
print(np.outer(A,B))

 0 1
 2 3


3
[[0 0]
 [2 3]]
